name = "tasks" # todo
main = "./src/index.ts"
compatibility_date = "2023-04-16"

kv_namespaces = [
  { binding = "data", id = "8c7d7ee9b6bb4f8fa3ca9f30eaf8d897"}
]

[triggers]
crons = ["15 */5 * * *"]